export const TASK_TOOGLE = 'app/tasks/TASK_TOOGLE'
export const TASK_CREATE = 'app/tasks/TASK_CREATE'
export const TASK_DELETE = 'app/tasks/TASK_DELETE'
export const TASK_UPDATE = 'app/tasks/TASK_UPDATE'
export const FETCHING = 'app/tasks/FETCHING'
export const FETCHED = 'app/tasks/FETCHED'
export const FETCH_FAILED = 'app/tasks/FETCH_FAILED'
